app/main/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import SubmitField, TextAreaField, StringField
from wtforms.validators import DataRequired


class PostForm(Form):
    """
    发表微博表单
    """
    body = TextAreaField("What's on your mind?", validators=[DataRequired()])
    submit = SubmitField('发布微博')


class CommentForm(Form):
    """	CommentForm	"""
    body = StringField('', validators=[DataRequired()])
    submit = SubmitField('发布评论')

app/main/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from ..models import Permission

main = Blueprint('main', __name__)


@main.app_context_processor
def inject_permissions():
    """
    :summary: 把Permission类加入模板上下文，这样就不需要每次都在路由中多传入一个参数了
    :return:
    """
    return dict(Permission=Permission)

# 在最后导入是为了防止循环导入
from . import errors, views

app/main/views.py
# -*- coding: utf-8 -*-
from . import main
from app import db
from flask import render_template, redirect
from flask import url_for, flash, abort, request
from flask import current_app, make_response
from app.models import User, Permission, Post, Comment
from .forms import PostForm, CommentForm
from flask_login import current_user, login_required
import os
from config import basedir
from ..decorators import permission_required


# 路由装饰器由蓝本提供
@main.route('/', methods=['GET', 'POST'])
def index():
    """
    :summary: 首页，包含一个发表post的表单
    :return:
    """
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            body=form.body.data,
            author=current_user._get_current_object()
        )
        db.session.add(post)
        db.session.commit()
        # 创建一个文件夹来存储文章对应的图片
        os.system('mkdir %s/app/static/img/posts/%s' % (basedir, post.id))
        return redirect(url_for('main.index'))
        # 为了显示某页中的记录， 要把 all() 换成 Flask-SQLAlchemy 提供的 paginate() 方法。
        # 页数是 paginate() 方法的第一个参数，也是唯一必需的参数。可选参数 per_page 用来指定每页显示的记录数量；
        # 如果没有指定，则默认显示 20 个记录。
        # 另一个可选参数为 error_out，当其设为 True 时（默认值），如果请求的页数超出了范围，则会返回 404 错误；
        # 如果设为 False，页数超出范围时会返回一个空列表。
    page = request.args.get('page', 1, type=int)
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    pagination = query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('main/index.html', form=form, posts=posts,
                           show_followed=show_followed, pagination=pagination)


@main.route('/users/<username>')
def users(username):
    """
    :summary: 用户个人主页视图函数
    :param username:
    :return:
    """
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    page = request.args.get('page', 1, type=int)
    pagination = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False
    )
    posts = pagination.items
    return render_template(
        'main/users.html', user=user, posts=posts, pagination=pagination)


@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    """
    :summary: 关注用户视图函数
    :param username:
    :return:
    """
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('用户不存在')
        return redirect(url_for('main.index'))
    if current_user.is_following(user):
        return redirect(url_for('main.users', username=username))
    current_user.follow(user)
    flash('成功关注了用户%s' % username)
    return redirect(url_for('main.users', username=username))


@main.route('/unfollow/<username>')
@login_required
def unfollow(username):
    """
    :summary: 取消关注视图函数
    :param username:
    :return:
    """
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('用户不存在')
        return redirect(url_for('main.index'))
    if not current_user.is_following(user):
        flash('您并未关注此用户')
        return redirect(url_for('main.users', username=username))
    current_user.unfollow(user)
    flash('成功取消关注了用户%s' % username)
    return redirect(url_for('main.users', username=username))


@main.route('/followers/<username>')
def followers(username):
    """
    :summary: 粉丝列表页面视图函数
    :param username:
    :return:
    """
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('用户不存在')
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.paginate(
        page, per_page=current_app.config['FOLLOWERS_PER_PAGE'],
        error_out=False
    )
    follows = [{'user': item.follower, 'timestamp': item.timestamp}
               for item in pagination.items]
    return render_template(
        'main/follows.html', user=user, endpoint='main.followers',
        title="粉丝", pagination=pagination, follows=follows)


@main.route('/followed-by/<username>')
def followed(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('用户不存在')
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followed.paginate(
        page, per_page=current_app.config['FOLLOWERS_PER_PAGE'],
        error_out=False)
    follows = [{'user': item.followed, 'timestamp': item.timestamp}
               for item in pagination.items]
    return render_template(
        'main/follows.html', user=user, title="关注",
        endpoint='.followed', pagination=pagination,
        follows=follows)


@main.route('/all')
@login_required
def show_all():
    resp = make_response(redirect(url_for('main.index')))
    resp.set_cookie('show_followed', '', max_age=30 * 24 * 60 * 60)
    return resp


@main.route('/followed')
@login_required
def show_followed():
    resp = make_response(redirect(url_for('main.index')))
    resp.set_cookie('show_followed', '1', max_age=30 * 24 * 60 * 60)
    return resp


@main.route('/post/<int:id>', methods=['POST', 'GET'])
def post(id):
    """
    :summary:
    :id:
    :return:
    """
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(
            body=form.body.data, post=post, author=current_user._get_current_object())
        db.session.add(comment)
        return redirect(url_for('main.post', id=post.id))
    comments = post.comments.order_by(Comment.timestamp.desc()).all()
    return render_template('main/post.html', posts=[post], comments=comments, form=form)

app/templates/main/follows.html
{% extends "base.html" %}

{% block page_content %}
    <div class="col">
        <!-- 上方图片或发表框 -->
        <div style="background:transparent; background-size:cover">
            <div class="wrapper-lg bg-white-opacity">
                <div class="row m-t">
                    <!-- 左边用户信息 -->
                    <div class="col-sm-7">
                        <!-- 头像 -->
                        <a href="{{ url_for('main.users', username=user.username) }}" class="thumb-lg pull-left m-r">
                            {% if user.avatar %}
                                <img src="../static/img/avatar/{{ user.avatar }}" class="img-circle" alt="...">
                            {% else %}
                                <img src="../static/img/avatar/avatar.jpg" class="img-circle" alt="...">
                            {% endif %}
                        </a>
                        <!-- 其他信息 -->
                        <div class="clear m-b">
                            <!-- 名字 -->
                            <div class="m-b m-t-sm">
                                <span class="h3 text-black">{{ user.username }}</span>
                                {% if user.location %}
                                    <small class="m-l">{{ user.location }}</small>
                                {% endif %}
                            </div>
                            <!-- 个人简介 -->
                            {% if  user.about_me  %}
                                <p class="m-b">
                                    {{ user.about_me }}
                                </p>
                            {% endif %}
                            <!-- 关注按钮 -->
                            {% if current_user.can(Permission.FOLLOW) and user != current_user %}
                                {% if current_user.is_following(user) %}
                                    <a href="{{ url_for('main.unfollow', username=user.username) }}" class="btn btn-sm btn-success btn-rounded">取消关注</a>
                                {% else %}
                                    <a href="{{ url_for('main.follow', username=user.username) }}" class="btn btn-sm btn-success btn-rounded">关注</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                    <!-- 右边用户粉丝信息 -->
                    <div class="col-sm-5">
                        <div class="pull-right pull-none-xs text-center">
                            <a href="{{ url_for('main.followers', username=user.username) }}" class="m-b-md inline m"><span class="h3 block font-bold">{{ user.followers.count() }}</span><small>粉丝</small></a>
                            <a href="{{ url_for('main.followed', username=user.username) }}" class="m-b-md inline m"><span class="h3 block font-bold">{{ user.followed.count() }}</span><small>关注</small>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- 中间导航条 -->
        <div class="wrapper bg-white b-b">
            <ul class="nav nav-pills nav-sm">
                {% if endpoint=='main.followers' %}
                    <li class="active"><a href="{{ url_for('main.followers', username=user.username) }}">粉丝</a></li>
                    <li><a href="{{ url_for('main.followed', username=user.username) }}">关注</a></li>
                {% else %}
                    <li><a href="{{ url_for('main.followers', username=user.username) }}">粉丝</a></li>
                    <li class="active"><a href="{{ url_for('main.followed', username=user.username) }}">关注</a></li>
                {% endif %}
                <li><a href>Messages</a></li>
            </ul>
        </div>
        <!-- 下方列表 -->
        <div class="padder">
            <div class="streamline b-l b-info m-l-lg m-b padder-v">
                <!-- 导入粉丝/关注列表 -->
                <ul class="follows">
                    {% for follow in follows %}
                        <!-- 文字微博和一句话神回复 -->
                        <li>
                            <!-- 头像 -->
                            <a class="pull-left thumb-sm avatar m-l-n-md" href="{{ url_for('main.users', username=follow.user.username) }}">

                                <img src="../static/img/avatar/{{ follow.user.avatar }}" class="img-circle" alt="...">

                            </a>
                            <div class="m-l-lg">
                                <!-- 昵称和发表时间 -->
                                <div class="m-b-xs">
                                    <a href="{{ url_for('main.users', username=follow.user.username) }}" class="h4">{{ follow.user.username }}</a>
                                    <span class="text-muted m-l-sm pull-right"> {{ moment( follow.timestamp).fromNow() }}</span>
                                </div>
                                <!-- 微博内容 -->
                                <div class="m-b">
                                    <p>简介：{{ follow.user.about_me }}</p>
                                    <p>地区：{{ follow.user.location }}</p>
                                    <!-- 工具条 -->
                                    <div>
                                    {% if current_user.can(Permission.FOLLOW) and follow.user != current_user %}
                                        {% if current_user.is_following(follow.user) %}
                                            <a href="{{ url_for('main.unfollow', username=follow.user.username) }}" class="btn btn-sm btn-success btn-rounded">取消关注</a>
                                        {% else %}
                                            <a href="{{ url_for('main.follow', username=follow.user.username) }}" class="btn btn-sm btn-success btn-rounded">关注</a>
                                        {% endif %}
                                    {% endif %}
                                    </div>

                                </div>
                            </div>

                        </li>
                    {% endfor %}

                </ul>
                {{ pagination_widget(pagination, endpoint, username=user.username) }}

            </div>
        </div>
    </div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}

{% block page_content %}
    <div class="col">
        <!-- 上方图片或发表框 -->
        {% if current_user.can(Permission.WRITE_ARTICLE) %}


            <div class="panel panel-default m-t-md m-b-n-sm pos-rlt" style="margin: 10px 10px 0px 10px;">

                    <div style="margin: 10px">
                        <img src="../static/img/index-logo.png" width="200px" height="20px" />
                    </div>
                    <form  method="post">
                        {{ form.hidden_tag() }}
                        {{ render_field(form.body,class="form-control no-border",style="padding-left: 20px;", rows="6",placeholder="说几句呗...") }}
                    <div class="panel-footer bg-light lter">
                        {{ render_field(form.submit, class="btn btn-info pull-right btn-sm") }}
                        <ul class="nav nav-pills nav-sm">
                            <li><a href><i class="fa fa-camera text-muted"></i></a></li>
                            <li><a href><i class="fa fa-video-camera text-muted"></i></a></li>
                        </ul>
                    </div>
                    </form>
            </div>


        {% else %}
            <div style="background: transparent; background-size:cover">
                <div class="wrapper-lg bg-white-opacity">
                    <div class="row m-t">
                        <!-- 左边用户信息 -->
                        <div class="col-sm-7">
                            <!-- 头像 -->
                            <a href class="thumb-lg pull-left m-r"><img src="{{ url_for('static', filename='img/a0.jpg') }}" class="img-circle">
                            </a>
                            <!-- 其他信息 -->
                            <div class="clear m-b">
                                <!-- 名字 -->
                                <div class="m-b m-t-sm">
                                    <span class="h3 text-black">John.Smith</span>
                                    <small class="m-l">London, UK</small>
                                </div>
                                <!-- 社交网络链接 -->
                                <p class="m-b">
                                    <a href class="btn btn-sm btn-bg btn-rounded btn-default btn-icon"><i class="fa fa-twitter"></i></a>
                                    <a href class="btn btn-sm btn-bg btn-rounded btn-default btn-icon"><i class="fa fa-facebook"></i></a>
                                    <a href class="btn btn-sm btn-bg btn-rounded btn-default btn-icon"><i class="fa fa-google-plus"></i></a>
                                </p>
                                <!-- 关注按钮 -->
                                <a href class="btn btn-sm btn-success btn-rounded">Follow
                                </a>
                            </div>
                        </div>
                        <!-- 右边用户粉丝信息 -->
                        <div class="col-sm-5">
                            <div class="pull-right pull-none-xs text-center">
                                <a href class="m-b-md inline m"><span class="h3 block font-bold">2k</span><small>Followers</small></a>
                                <a href class="m-b-md inline m"><span class="h3 block font-bold">250</span><small>Following</small>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        {% endif %}
        <!-- 中间导航条 -->
        <div class="wrapper bg-white b-b">
            <ul class="nav nav-pills nav-sm">

                <li{% if not show_followed %} class="active"{% endif %}><a href="{{ url_for('main.show_all') }}">全部微博</a></li>
                {% if current_user.is_authenticated %}
        <li{% if show_followed %} class="active"{% endif %}><a href="{{ url_for('main.show_followed') }}">我的关注</a></li>
        {% endif %}


            </ul>
        </div>
        <!-- 下方文章列表 -->
        <div class="padder">
            <div class="streamline b-l b-info m-l-lg m-b padder-v">
                <!-- 导入文章列表模板 -->
                {% include "_posts.html" %}
                {{ pagination_widget(pagination, 'main.index') }}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/main/post.html
{% extends "base.html" %} {% block page_content %}
<div class="col">
    <!-- 下方文章列表 -->
    <div class="padder">
        <div class="streamline b-l b-info m-l-lg m-b padder-v">
            <!-- 导入文章列表模板 -->
            <ul class="posts">
                {% for post in posts %}
                <!-- 文字微博和一句话神回复 -->
                <li>
                    <!-- 头像 -->
                    <a class="pull-left thumb-sm avatar m-l-n-md" href="{{ url_for('main.users', username=post.author.username) }}">
                        <img src="../static/img/avatar/{{ post.author.avatar }}" class="img-circle" alt="...">
                    </a>
                    <div class="m-l-lg">
                        <!-- 昵称和发表时间 -->
                        <div class="m-b-xs">
                            <a href="{{ url_for('main.users', username=post.author.username) }}" class="h4">{{ post.author.username }}</a>
                            <span class="text-muted m-l-sm pull-right"> {{ moment( post.timestamp).fromNow() }}</span>
                        </div>
                        <!-- 微博内容 -->
                        <div class="m-b">
                            <p>{{ post.body }}</p>
                            <!-- 工具条 -->
                            <div class="m-t-sm">
                                <a href class="text-muted m-xs"><i class="icon-action-redo">转发</i></a>
                                <a href class="text-muted m-xs"><i class="icon-star"></i>收藏</a>
                            </div>
                        </div>
                    </div>
                    <!-- 评论 -->
                    <div class="m-l-lg" id="comment-block" class="comment-app-holder">
                        <div class="_commentBox-list">
                            {% include "_comments.html" %}
                        </div>
                    </div>

                    <div class="panel panel-default m-t-md m-b-n-sm pos-rlt" style="margin: 10px 10px 0px 50px;">

                
                    <form  method="post">
                    <div style="height: 80px;">
                        {{ form.hidden_tag() }}
                        {{ render_field(form.body,class="form-control no-border",rows="6",placeholder="说几句呗...") }}
                        </div>
                    <div class="panel-footer bg-light lter">
                        {{ render_field(form.submit, class="btn btn-info pull-right btn-sm") }}
                        <ul class="nav nav-pills nav-sm">
                            <li><a href><i class="fa fa-camera text-muted"></i></a></li>
                            <li><a href><i class="fa fa-video-camera text-muted"></i></a></li>
                        </ul>
                    </div>
                    </form>
            </div>

                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/users.html
{% extends "base.html" %}

{% block page_content %}
    <div class="col">
        <!-- 上方图片或发表框 -->
        <div style="background:transparent; background-size:cover">
            <div class="wrapper-lg bg-white-opacity">
                <div class="row m-t">
                    <!-- 左边用户信息 -->
                    <div class="col-sm-7">
                        <!-- 头像 -->
                        <a href="{{ url_for('main.users', username=user.username) }}" class="thumb-lg pull-left m-r">
                            {% if user.avatar %}
                                <img src="../static/img/avatar/{{ user.avatar }}" class="img-circle" alt="...">
                            {% else %}
                                <img src="../static/img/avatar/avatar.jpg" class="img-circle" alt="...">
                            {% endif %}
                        </a>
                        <!-- 其他信息 -->
                        <div class="clear m-b">
                            <!-- 名字 -->
                            <div class="m-b m-t-sm">
                                <span class="h3 text-black">{{ user.username }}</span>
                                {% if user.location %}
                                    <small class="m-l">{{ user.location }}</small>
                                {% endif %}
                            </div>
                            <!-- 个人简介 -->
                            {% if  user.about_me  %}
                                <p class="m-b">
                                    {{ user.about_me }}
                                </p>
                            {% endif %}
                            <!-- 关注按钮 -->
                            {% if current_user.can(Permission.FOLLOW) and user != current_user %}
                                {% if current_user.is_following(user) %}
                                    <a href="{{ url_for('main.unfollow', username=user.username) }}" class="btn btn-sm btn-success btn-rounded">取消关注</a>
                                {% else %}
                                    <a href="{{ url_for('main.follow', username=user.username) }}" class="btn btn-sm btn-success btn-rounded">关注</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                    <!-- 右边用户粉丝信息 -->
                    <div class="col-sm-5">
                        <div class="pull-right pull-none-xs text-center">
                            <a href="{{ url_for('main.followers', username=user.username) }}" class="m-b-md inline m"><span class="h3 block font-bold">{{ user.followers.count() - 1 }}</span><small>粉丝</small></a>
                            <a href="{{ url_for('main.followed', username=user.username) }}" class="m-b-md inline m"><span class="h3 block font-bold">{{ user.followed.count() - 1 }}</span><small>关注</small>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- 中间导航条 -->
        <div class="wrapper bg-white b-b">
            <ul class="nav nav-pills nav-sm">
                <li class="active"><a href>Stream</a></li>
                <li><a href>Profile</a></li>
                <li><a href>Messages</a></li>
            </ul>
        </div>
        <!-- 下方文章列表 -->
        <div class="padder">
            <div class="streamline b-l b-info m-l-lg m-b padder-v">
                <!-- 导入文章列表模板 -->
                {% include "_posts.html" %}
                {{ pagination_widget(pagination, 'main.users', username=user.username) }}
            </div>
        </div>
    </div>
{% endblock %}